version: 2
jobs:
  build:
    docker:
      - image: circleci/rust:latest
    steps:
      - checkout
      - run: git config --global user.email "you@example.com" && git config --global user.name "Your Name"
      - run: cargo test -- --nocapture
